We should find the value of L and V that satisfy the this equation:
A . V == L * V

---



In [16]:
import numpy as np

In [17]:
A = np.array([[1,4],[3,2]])
print(A)

[[1 4]
 [3 2]]


In [18]:
L, V = np.linalg.eig(A)

In [19]:
L # Eigenvalues

array([-2.,  5.])

In [20]:
print(np.round(V, decimals=1)) #Eigenvectors

[[-0.8 -0.7]
 [ 0.6 -0.7]]


In [21]:
L[0] * V[:, 0]

array([ 1.6, -1.2])

In [22]:
np.dot(A, V[:, 0])

array([ 1.6, -1.2])

In [23]:
L[1] * V[:, 1]

array([-3.53553391, -3.53553391])

In [24]:
np.dot(A, V[:, 1])

array([-3.53553391, -3.53553391])