We should find the value of L and V that satisfy the this equation:
A . V == L * V

---



In [1]:
import numpy as np

In [2]:
A = np.array([[1,4],[3,2]])
print(A)

[[1 4]
 [3 2]]


In [3]:
L, V = np.linalg.eig(A)

In [4]:
L # Eigenvalues

array([-2.,  5.])

In [5]:
print(np.round(V, decimals=1)) #Eigenvectors

[[-0.8 -0.7]
 [ 0.6 -0.7]]


In [6]:
L[0] * V[:, 0]

array([ 1.6, -1.2])

In [7]:
np.dot(A, V[:, 0])

array([ 1.6, -1.2])

In [8]:
L[1] * V[:, 1]

array([-3.53553391, -3.53553391])

In [9]:
np.dot(A, V[:, 1])

array([-3.53553391, -3.53553391])

In [10]:
import sympy as sp

In [11]:
A = sp.Matrix([[1,4],[3,2]])
A

Matrix([
[1, 4],
[3, 2]])

In [13]:
A.eigenvals()

{5: 1, -2: 1}

In [15]:
A.eigenvects()

[(-2,
  1,
  [Matrix([
   [-4/3],
   [   1]])]),
 (5,
  1,
  [Matrix([
   [1],
   [1]])])]