In [3]:
import numpy as np

In [4]:
# array

In [5]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [6]:
a[2]

4

In [7]:
a.dtype

dtype('int32')

In [8]:
a.shape

(3,)

In [9]:
b = np.array([(1,2),(3,4),(5,6)])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
b[1,1]

4

In [11]:
b[: , 1]

array([2, 4, 6])

In [12]:
b[0:2, 1]

array([2, 4])

In [13]:
b[1, :]

array([3, 4])

In [14]:
b.ndim

2

In [15]:
b.shape

(3, 2)

In [16]:
c = np.reshape(b, (2,3))
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.shape

(2, 3)

In [18]:
d = np.reshape(b, (1,-1))
d

array([[1, 2, 3, 4, 5, 6]])

In [19]:
d.shape

(1, 6)

In [20]:
e = np.reshape(b, (-1,1))
e

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
e.shape

(6, 1)

In [22]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
b < 3

array([[ True,  True],
       [False, False],
       [False, False]])

In [24]:
x = np.array([(1,2),(3,4)])
x

array([[1, 2],
       [3, 4]])

In [25]:
y = np.array([(5,6),(7,8)])
y

array([[5, 6],
       [7, 8]])

In [26]:
x * y

array([[ 5, 12],
       [21, 32]])

In [27]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [28]:
y.dot(x)

array([[23, 34],
       [31, 46]])

In [ ]:
# arange

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [57]:
np.arange(1, 9, step=2)

array([1, 3, 5, 7])

In [59]:
np.arange(6).reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [61]:
 # linspace - The distances are equal

In [65]:
np.linspace(1, 9, num=6)

array([1. , 2.6, 4.2, 5.8, 7.4, 9. ])

In [67]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [69]:
# zeros, ones, empty, full, eye

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.ones(4)

array([1., 1., 1., 1.])

In [91]:
np.empty(18)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 1.42418444e-306,
       7.56602523e-307, 1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
       1.11260619e-306, 8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
       1.37962456e-306, 1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
       7.56599807e-307, 1.69119330e-306])

In [85]:
np.full((2,3),3)

array([[3, 3, 3],
       [3, 3, 3]])

In [97]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [99]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
# Universal Functions

In [106]:
t = np.arange(3)
t

array([0, 1, 2])

In [108]:
np.sqrt(t)

array([0.        , 1.        , 1.41421356])

In [110]:
np.exp(t)

array([1.        , 2.71828183, 7.3890561 ])

In [138]:
k = np.array([(3, 1, 6), (4, 0, 6)])
k

array([[3, 1, 6],
       [4, 0, 6]])

In [140]:
k.sum(axis=0)

array([ 7,  1, 12])

In [142]:
k.sum(axis=1)

array([10, 10])

In [144]:
k.min(axis=0)

array([3, 0, 6])

In [146]:
k.min(axis=1)

array([1, 0])

In [148]:
k.max(axis=0)

array([4, 1, 6])

In [150]:
np.sort(k)

array([[1, 3, 6],
       [0, 4, 6]])

In [154]:
np.sort(k, axis=None)

array([0, 1, 3, 4, 6, 6])

In [156]:
# Random

In [162]:
np.random.randint(5)

2

In [176]:
np.random.seed(1)
np.random.randint(5)

3

In [166]:
np.random.randint(4, size=(2,3))

array([[2, 1, 2],
       [3, 0, 1]])

In [168]:
np.random.rand(5)  # [0, 1)

array([0.62340585, 0.96567655, 0.74404872, 0.48614923, 0.12453469])

In [170]:
np.random.rand(3)

array([0.87851153, 0.30873195, 0.53084668])

In [178]:
 np.random.uniform(0, 4, size=(3,4)) # Uniform distribution

array([[2.88129797e+00, 4.57499269e-04, 1.20933029e+00, 5.87023563e-01],
       [3.69354379e-01, 7.45040846e-01, 1.38224291e+00, 1.58706990e+00],
       [2.15526694e+00, 1.67677806e+00, 2.74087800e+00, 8.17808999e-01]])

In [180]:
np.random.randn(4) # Std Normal distribution

array([-0.85990661,  1.77260763, -1.11036305,  0.18121427])