In [2]:
import tensorflow as tf
tf.__version__

'2.19.0'

In [ ]:
# Scalar
x = tf.constant(10)
print(x)
print(x.shape)
print(x.ndim)

tf.Tensor(4, shape=(), dtype=int32)
()
0


In [ ]:
# Vector
y = tf.constant([1, 2, 3])
print(y)
print(y.shape)
print(y.ndim)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
(3,)
1


In [24]:
# Matrix
u = tf.constant([[1, 2, 3], 
                 [4, 5, 6]])
print(u)
print(u.shape)
print(u.ndim)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
(2, 3)
2


In [3]:
u = tf.constant([[1, 2, 3], [4, 5, 6]])
v = tf.constant([[7, 8, 9], [10, 11, 12]])

In [4]:
print(u + v)

tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)


In [6]:
print(tf.constant(4) * u)

tf.Tensor(
[[ 4  8 12]
 [16 20 24]], shape=(2, 3), dtype=int32)


In [7]:
print(u * v)

tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32)


In [14]:
x = tf.matmul(u, v, transpose_a=True)
print(x)

tf.Tensor(
[[47 52 57]
 [64 71 78]
 [81 90 99]], shape=(3, 3), dtype=int32)


In [17]:
u @ tf.transpose(v)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50,  68],
       [122, 167]])>

In [18]:
v @ tf.transpose(u)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 50, 122],
       [ 68, 167]])>

In [29]:
# Tensor
A = tf.linspace(1, 60, 60)
print(A)

tf.Tensor(
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53. 54.
 55. 56. 57. 58. 59. 60.], shape=(60,), dtype=float64)


In [30]:
A = tf.reshape(A, shape=(5, 2, 6))
print(A)

tf.Tensor(
[[[ 1.  2.  3.  4.  5.  6.]
  [ 7.  8.  9. 10. 11. 12.]]

 [[13. 14. 15. 16. 17. 18.]
  [19. 20. 21. 22. 23. 24.]]

 [[25. 26. 27. 28. 29. 30.]
  [31. 32. 33. 34. 35. 36.]]

 [[37. 38. 39. 40. 41. 42.]
  [43. 44. 45. 46. 47. 48.]]

 [[49. 50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59. 60.]]], shape=(5, 2, 6), dtype=float64)


In [31]:
tf.reshape(A, shape=(5, 2, 3, 2))

<tf.Tensor: shape=(5, 2, 3, 2), dtype=float64, numpy=
array([[[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]],


       [[[13., 14.],
         [15., 16.],
         [17., 18.]],

        [[19., 20.],
         [21., 22.],
         [23., 24.]]],


       [[[25., 26.],
         [27., 28.],
         [29., 30.]],

        [[31., 32.],
         [33., 34.],
         [35., 36.]]],


       [[[37., 38.],
         [39., 40.],
         [41., 42.]],

        [[43., 44.],
         [45., 46.],
         [47., 48.]]],


       [[[49., 50.],
         [51., 52.],
         [53., 54.]],

        [[55., 56.],
         [57., 58.],
         [59., 60.]]]])>