In [1]:
import numpy as np

In [2]:
a = np.array([[6, 4, 24], [1, -9, 8]])

In [3]:
print(a)

[[ 6  4 24]
 [ 1 -9  8]]


In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(2, 3)

In [6]:
a[0]

array([ 6,  4, 24])

In [7]:
a[0][0]

6

In [8]:
a[:, 0]

array([6, 1])

In [9]:
a[:, 1]

array([ 4, -9])

In [10]:
a = np.array([[6, 4, 24], [1, -9, 8], [1, 2, 4]])

In [11]:
print(a)

[[ 6  4 24]
 [ 1 -9  8]
 [ 1  2  4]]


In [12]:
a[0:2]

array([[ 6,  4, 24],
       [ 1, -9,  8]])

In [13]:
a[1:3]

array([[ 1, -9,  8],
       [ 1,  2,  4]])

In [14]:
a[0:2, :2]

array([[ 6,  4],
       [ 1, -9]])

In [15]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [16]:
a.sum()

21

In [17]:
a.sum(axis=0) #Column

array([5, 7, 9])

In [18]:
a.sum(axis=1) #Row

array([ 6, 15])

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [20]:
print(a + b)

[[2 4]
 [6 8]]


In [21]:
print(a - b)

[[0 0]
 [0 0]]


In [22]:
print(a * b)

[[ 1  4]
 [ 9 16]]


In [23]:
np.dot(a, b)

array([[ 7, 10],
       [15, 22]])

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [25]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [26]:
a.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a = np.array([[0, 1, 2], [1, 7, 8], [2, 8, 9]])
print(a)

[[0 1 2]
 [1 7 8]
 [2 8 9]]


In [28]:
b = a.T

In [29]:
a == b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [30]:
np.trace(a)

16

In [31]:
np.trace(b)

16

In [32]:
x = np.array([[8,3], [4,2]])
print(x)

[[8 3]
 [4 2]]


In [33]:
np.linalg.det(x)

3.999999999999999

In [34]:
y = np.array([[1,2,3], [3,1,2],[0,0,1]])
print(y)

[[1 2 3]
 [3 1 2]
 [0 0 1]]


In [35]:
np.linalg.det(x)

3.999999999999999

In [36]:
a = np.array([[4,3], [3,2]])
print(a)

[[4 3]
 [3 2]]


In [37]:
b = np.linalg.inv(a)
print(b)

[[-2.  3.]
 [ 3. -4.]]


In [38]:
print(np.dot(a, b))

[[1. 0.]
 [0. 1.]]


In [39]:
np.linalg.norm(a)

6.164414002968976

In [40]:
np.sqrt(np.trace(a.dot(a.T)))

6.164414002968976

In [41]:
import sympy as sp

In [42]:
a = sp.Matrix([[-6,3], [4,5]])
a

Matrix([
[-6, 3],
[ 4, 5]])

In [43]:
a.row(0)

Matrix([[-6, 3]])

In [44]:
a.col(0)

Matrix([
[-6],
[ 4]])

In [45]:
a.shape

(2, 2)

In [46]:
a.inv()

Matrix([
[-5/42, 1/14],
[ 2/21,  1/7]])

In [47]:
a.det()

-42

In [48]:
sp.zeros(4, 5)

Matrix([
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0],
[0, 0, 0, 0, 0]])

In [49]:
sp.eye(5,5)

Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 0],
[0, 0, 0, 1, 0],
[0, 0, 0, 0, 1]])

In [50]:
sp.diag(1,2,3,4)

Matrix([
[1, 0, 0, 0],
[0, 2, 0, 0],
[0, 0, 3, 0],
[0, 0, 0, 4]])