We aim to write matrix A as: A = U.S.Vt

In [3]:
import numpy as np

In [5]:
A = np.array([[3,1,1], [-1,3,1]])

In [6]:
np.dot(A, A.T)

array([[11,  1],
       [ 1, 11]])

In [7]:
np.dot(A.T, A)

array([[10,  0,  2],
       [ 0, 10,  4],
       [ 2,  4,  2]])

In [8]:
U, S, Vt = np.linalg.svd(A)

In [13]:
print(np.round(U, decimals=1))

[[-0.7 -0.7]
 [-0.7  0.7]]


In [15]:
print(np.round(S, decimals=1))

[3.5 3.2]


In [17]:
print(np.round(Vt, 1))

[[-0.4 -0.8 -0.4]
 [-0.9  0.4  0. ]
 [-0.2 -0.4  0.9]]


In [20]:
S = np.array([[3.5, 0, 0],
              [0, 3.2, 0]])

In [21]:
X = np.dot(U, np.dot(S, Vt))

In [23]:
np.round(X, 1)

array([[ 3.,  1.,  1.],
       [-1.,  3.,  1.]])

In [24]:
A

array([[ 3,  1,  1],
       [-1,  3,  1]])